### ISSUE TITLE
Error Loading Modpack

### ISSUE THREAD

**Issue by Angellmc420** [NotSoEpic/deepdrilling#19]
[debug.log](https://github.com/user-attachments/files/18045479/debug.log)
[latest.log](https://github.com/user-attachments/files/18045481/latest.log)

We had deep drilling then removed it for space. Is that the cause? And would reinstalling it fix the issue?

**Comment by NotSoEpic** [comment]
It seems you're using version 1.0.2
This problem was fixed in 1.1.0, so try updating

Also be warned if you remove a mod and then load chunks, any blocks from that mod will be replaced by air in those chunks- even if the mod is added back in
(Modded structure data will also be removed breaking /locate for nodes placed in those loaded chunks, but in your version ore nodes are features)

**Comment by DrowningFish233** [comment]
In fact, he still can't run it on neoforge.

Look here.:
https://github.com/CraftTweaker/CraftTweaker/issues/1785

**Comment by BeeIsYou** [comment]
#13 has been fixed and will be included in the next update
